// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PJATK_APBD_SALE_KONFERENCYJNE_EFCore_CodeFirst_ver2.Data;

#nullable disable

namespace PJATK_APBD_SALE_KONFERENCYJNE_EFCore_CodeFirst_ver2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PJATK_APBD_SALE_KONFERENCYJNE_EFCore_CodeFirst_ver2.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("PJATK_APBD_SALE_KONFERENCYJNE_EFCore_CodeFirst_ver2.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("RoomId");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("PJATK_APBD_SALE_KONFERENCYJNE_EFCore_CodeFirst_ver2.Models.RoomAccess", b =>
                {
                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("Room_ID");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("Employee_ID");

                    b.HasKey("RoomId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("RoomAccess");
                });

            modelBuilder.Entity("PJATK_APBD_SALE_KONFERENCYJNE_EFCore_CodeFirst_ver2.Models.RoomBooking", b =>
                {
                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("Room_ID");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("Employee_ID");

                    b.Property<DateTime?>("BookingEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BookingStart")
                        .HasColumnType("datetime2");

                    b.HasKey("RoomId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("RoomBooking");
                });

            modelBuilder.Entity("PJATK_APBD_SALE_KONFERENCYJNE_EFCore_CodeFirst_ver2.Models.RoomAccess", b =>
                {
                    b.HasOne("PJATK_APBD_SALE_KONFERENCYJNE_EFCore_CodeFirst_ver2.Models.Employee", "Employee")
                        .WithMany("RoomAccesses")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PJATK_APBD_SALE_KONFERENCYJNE_EFCore_CodeFirst_ver2.Models.Room", "Room")
                        .WithMany("RoomAccesses")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("PJATK_APBD_SALE_KONFERENCYJNE_EFCore_CodeFirst_ver2.Models.RoomBooking", b =>
                {
                    b.HasOne("PJATK_APBD_SALE_KONFERENCYJNE_EFCore_CodeFirst_ver2.Models.Employee", "Employee")
                        .WithMany("RoomBookings")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PJATK_APBD_SALE_KONFERENCYJNE_EFCore_CodeFirst_ver2.Models.Room", "Room")
                        .WithMany("RoomBookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("PJATK_APBD_SALE_KONFERENCYJNE_EFCore_CodeFirst_ver2.Models.Employee", b =>
                {
                    b.Navigation("RoomAccesses");

                    b.Navigation("RoomBookings");
                });

            modelBuilder.Entity("PJATK_APBD_SALE_KONFERENCYJNE_EFCore_CodeFirst_ver2.Models.Room", b =>
                {
                    b.Navigation("RoomAccesses");

                    b.Navigation("RoomBookings");
                });
#pragma warning restore 612, 618
        }
    }
}
